# Generated by Django 4.2.9 on 2024-01-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weed_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('prod_id', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='products',
            name='count_pack',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.TextField(default='Создан', null=True),
        ),
    ]
