# Generated by Django 4.2.9 on 2024-01-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weed_site', '0005_session_remove_user_is_active_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.AddField(
            model_name='products',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
