# Generated by Django 4.2.9 on 2024-01-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weed_site', '0007_orders_admin_mess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.TextField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
