# Generated by Django 4.2.9 on 2024-01-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weed_site', '0004_remove_user_login_remove_user_password_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('cookie', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
