# Generated by Django 4.2.9 on 2024-01-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weed_site', '0006_category_delete_session_products_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='admin_mess',
            field=models.TextField(null=True),
        ),
    ]
