# Generated by Django 4.2.9 on 2024-01-15 09:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weed_site', '0009_alter_user_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('pics', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('content', models.TextField(null=True)),
            ],
        ),
    ]
