# Generated by Django 4.2.9 on 2024-01-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weed_site', '0010_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='pay',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='post',
            field=models.TextField(null=True),
        ),
    ]
