# Generated by Django 4.2.9 on 2024-01-18 16:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weed_site', '0013_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=[], null=True, size=None),
        ),
    ]
