# Generated by Django 4.2.9 on 2024-01-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weed_site', '0014_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='prods_dict',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
